### ISSUE TITLE
有没有实际的测试对比图呢？

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [ichynul/auto-process#1]
类似于，不使用这个库之前的并发，和用了这个库之后的并发数的截图对比，这样能路由说服力

**Comment by ichynul** [comment]
没有测试过，希望有人能在linux上测试并分享出来。
这个库存在的意义主要是在windows上面增加系统性能。
linux上要在使用nginx时才有可比性，nginx+多process多端口与nginx+单端口去比较。
而且这个库在linux上使用的目的也不是非要比单端口的性能强，而是因为nginx毕竟是成熟的解决方案，在负载均衡方面有些可配置的选项，比如`ip_hash`、`least_conn`等。

**Comment by Mr-ShiHuaYu** [comment]
用你这个库的肯定就是windows了，linux的东西就没必要说了。
至于你说的"这个库存在的意义主要是在windows上面增加系统性能。"，这句话，能增加性能？有没有测试过？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 中午12:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ichynul/auto-process] 有没有实际的测试对比图呢？ (Issue #1)




 
没有测试过，希望有人能在linux上测试并分享出来。
 这个库存在的意义主要是在windows上面增加系统性能。
 linux上要在使用nginx时才有可比性，nginx+多process多端口与nginx+单端口去比较。
 而且这个库在linux上使用的目的也不是非要比单端口的性能强，而是因为nginx毕竟是成熟的解决方案，在负载均衡方面有些可配置的选项，比如ip_hash、least_conn等。

**Comment by ichynul** [comment]
> 

widows用就对了。widows上不支持多线程的，`config/server.php`里面的`count`设置是无效的，都是单线程，同时多个请求进入是阻塞的。如果不开多process+nginx、apache等代理，那widows上是没办法用于生产环境的。
https://www.workerman.net/q/10247
https://www.workerman.net/q/10238

**Comment by Mr-ShiHuaYu** [comment]
这是理论，我就是问问你有没有实际测试过的图。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 中午1:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ichynul/auto-process] 有没有实际的测试对比图呢？ (Issue #1)




   
widows用就对了。widows上不支持多线程的，config/server.php里面的count设置是无效的，都是单线程，同时多个请求进入是阻塞的。如果不开多process+nginx、apache等代理，那widows上是没办法用于生产环境的。
 https://www.workerman.net/q/10247
 https://www.workerman.net/q/10238

**Comment by ichynul** [comment]
> 

这东西没必要测试，如果你觉得我说的不可信，可以到官方论坛去了解widows在使用方面的问题。

**Comment by Mr-ShiHuaYu** [comment]
信，当然相信。我打算用webman在windows Server下，所以关注这个框架能不能正常用在生产环境



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 中午1:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ichynul/auto-process] 有没有实际的测试对比图呢？ (Issue #1)




   
这东西没必要测试，如果你觉得我说的不可信，可以到官方论坛去了解widows在使用方面的问题。

**Comment by Mr-ShiHuaYu** [comment]
那process_count在windows上应该写什么呢？8的话，是8进程么？也就是同时可以8个人访问么？这块不太懂，麻烦大佬解答

**Comment by ichynul** [comment]
填`8`是同时启动了`8`个`php.exe`程序，框架默认的一个`1`个+7个`process`。

**Comment by Mr-ShiHuaYu** [comment]
那请问并发用户数是8么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ichynul/auto-process] 有没有实际的测试对比图呢？ (Issue #1)




 
填8是同时启动了8个php.exe程序，框架默认的一个1个+7个process。
